// <auto-generated />
using System;
using Octoplex.Produtos.Infra.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Octoplex.Produtos.Infra.Data.Migrations
{
    [DbContext(typeof(ProdutoDbContext))]
    [Migration("20230125000125_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CK.Impostos.Domain.Impostos.Imposto", b =>
                {
                    b.Property<int>("IdImposto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImposto"), 1L, 1);

                    b.Property<double>("AliqCofins")
                        .HasColumnType("float");

                    b.Property<double>("AliqIcms")
                        .HasColumnType("float");

                    b.Property<double>("AliqIpi")
                        .HasColumnType("float");

                    b.Property<double>("AliqPis")
                        .HasColumnType("float");

                    b.Property<string>("Cest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cfop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoSefaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodigoUf")
                        .HasColumnType("int");

                    b.Property<string>("Csosn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CstCofins")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CstIcms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CstIpi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CstPis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("IbptAliq")
                        .HasColumnType("float");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int");

                    b.Property<string>("Ncm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("int");

                    b.HasKey("IdImposto");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Impostos");
                });

            modelBuilder.Entity("CK.Produtos.Domain.Produtos.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Balanca")
                        .HasColumnType("bit")
                        .HasColumnName("Balanca");

                    b.Property<int>("CodGru")
                        .HasColumnType("int")
                        .HasColumnName("CodGru");

                    b.Property<string>("CodPf")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CodigoNoFornecedor");

                    b.Property<string>("Codigo")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("Codigo");

                    b.Property<string>("Codigoanp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CodigoAnp");

                    b.Property<string>("Descricao")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Descricao");

                    b.Property<string>("DivForn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DivForn");

                    b.Property<string>("DtAlt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DataAlteracao");

                    b.Property<string>("DtUltvenda")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DtUltvenda");

                    b.Property<double>("EstMin")
                        .HasColumnType("float")
                        .HasColumnName("EstMin");

                    b.Property<double>("Estq")
                        .HasColumnType("float")
                        .HasColumnName("Estoque");

                    b.Property<string>("FimPromo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FimPromo");

                    b.Property<int>("Forn1")
                        .HasColumnType("int")
                        .HasColumnName("idFornecedor1");

                    b.Property<int>("Forn2")
                        .HasColumnType("int")
                        .HasColumnName("idFornecedor2");

                    b.Property<string>("Guid")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GuidIntegracao");

                    b.Property<int>("IdEmp")
                        .HasColumnType("int")
                        .HasColumnName("idEmpresa");

                    b.Property<string>("ImpCoz")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImprimeCozinha");

                    b.Property<int?>("ImpostoIdImposto")
                        .HasColumnType("int");

                    b.Property<string>("IniPromo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IniPromo");

                    b.Property<double>("Lucro")
                        .HasColumnType("float")
                        .HasColumnName("Lucro");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<string>("TeclaB")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TeclaBalanca");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tipo");

                    b.Property<string>("Un")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Un");

                    b.Property<string>("Validade")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Validade");

                    b.Property<double>("ValorA")
                        .HasColumnType("float")
                        .HasColumnName("ValorA");

                    b.Property<double>("ValorB")
                        .HasColumnType("float")
                        .HasColumnName("ValorB");

                    b.Property<double>("Valultvenda")
                        .HasColumnType("float")
                        .HasColumnName("Valultvenda");

                    b.Property<double>("Vrcompra")
                        .HasColumnType("float")
                        .HasColumnName("ValorCompra");

                    b.Property<double>("Vrvista")
                        .HasColumnType("float")
                        .HasColumnName("ValorVenda");

                    b.HasKey("Id");

                    b.HasIndex("ImpostoIdImposto");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("CK.Impostos.Domain.Impostos.Imposto", b =>
                {
                    b.HasOne("CK.Produtos.Domain.Produtos.Produto", null)
                        .WithMany("Impostos")
                        .HasForeignKey("ProdutoId");
                });

            modelBuilder.Entity("CK.Produtos.Domain.Produtos.Produto", b =>
                {
                    b.HasOne("CK.Impostos.Domain.Impostos.Imposto", "Imposto")
                        .WithMany()
                        .HasForeignKey("ImpostoIdImposto");

                    b.Navigation("Imposto");
                });

            modelBuilder.Entity("CK.Produtos.Domain.Produtos.Produto", b =>
                {
                    b.Navigation("Impostos");
                });
#pragma warning restore 612, 618
        }
    }
}
