// <auto-generated />
using Octoplex.Impostos.Infra.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Octoplex.Impostos.Infra.Data.Migrations
{
    [DbContext(typeof(ImpostoDbContext))]
    [Migration("20220328134028_AddTabelaImpostos")]
    partial class AddTabelaImpostos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CK.Impostos.Domain.Impostos.Imposto", b =>
                {
                    b.Property<int>("IdImposto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AliqCofins")
                        .HasColumnType("float")
                        .HasColumnName("AliqCofins");

                    b.Property<double>("AliqIcms")
                        .HasColumnType("float")
                        .HasColumnName("AliqIcms");

                    b.Property<double>("AliqIpi")
                        .HasColumnType("float")
                        .HasColumnName("AliqIpi");

                    b.Property<double>("AliqPis")
                        .HasColumnType("float")
                        .HasColumnName("AliqPis");

                    b.Property<string>("Cest")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Cest");

                    b.Property<string>("Cfop")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Cfop");

                    b.Property<string>("CodigoSefaz")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CodigoSefaz");

                    b.Property<string>("Csosn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Csosn");

                    b.Property<string>("CstCofins")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CstCofins");

                    b.Property<string>("CstIcms")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CstIcms");

                    b.Property<string>("CstIpi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CstIpi");

                    b.Property<string>("CstPis")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CstPis");

                    b.Property<double>("IbptAliq")
                        .HasColumnType("float")
                        .HasColumnName("IbptAliq");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int")
                        .HasColumnName("IdProduto");

                    b.Property<string>("Ncm")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ncm");

                    b.Property<string>("Origem")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Origem");

                    b.HasKey("IdImposto");

                    b.ToTable("Impostos");
                });
#pragma warning restore 612, 618
        }
    }
}
